version: 2
jobs:
  build:
    docker:
      - image: srcml/ubuntu_x86_64_base:latest

    steps:
      - checkout
      - run: ls
      - run: pwd
#      - run: g++ hello.cpp -o hello
#      - run: ./hello
